=begin
#Swagger Petstore

#This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

OpenAPI spec version: 1.0.0
Contact: apiteam@swagger.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Hello::HelloResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'HelloResponse' do
  before do
    # run before each test
    @instance = Hello::HelloResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HelloResponse' do
    it 'should create an instance of HelloResponse' do
      expect(@instance).to be_instance_of(Hello::HelloResponse)
    end
  end
end

