=begin
#Swagger Petstore

#This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

OpenAPI spec version: 1.0.0
Contact: apiteam@swagger.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'hello/api_client'
require 'hello/api_error'
require 'hello/version'
require 'hello/configuration'

# Models
require 'hello/models/hello'
require 'hello/models/hello_response'
require 'hello/models/square'
require 'hello/models/square_response'

# APIs
require 'hello/api/hello_api'
require 'hello/api/square_api'

module Hello
  class << self
    # Customize default settings for the SDK using block.
    #   Hello.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
